print("Please enter the number of lives")
lives=int(input())
print("Please enter the energy level")
energy_level = int(input())
print("Please enter the shield level")
shield_level = int(input())
print("Health level has been set")
print("\n")
print(f"Health: {'♥' *lives}")
print(f"Energy level: {'♠' * energy_level}")
print(f"Shield Level: {'♦' * shield_level}")
