print("Please enter the number of lives")
lives=str(input())
lives= str.replace("♥", "lives", "")
print("Please enter the energy level")
energy_level = str(input())
energy_level= str.replace("♠", "energy_level", "")
print("Please enter the shield level")
shield_level = str(input())
shield_level= str.replace("♦", "shield_level", "")
print("Health level has been set")
print("\n")
print(f"Health: {lives}")
print(f"Energy level: {energy_level}")
print(f"Shield Level: {shield_level}")
